In [30]:
import requests
import xml.etree.ElementTree as ET
import pandas as pd
from datetime import datetime, UTC
print("run successfully")

run successfully

In [31]:
RSS_FEEDS = [
    "https://hnrss.org/jobs",
    "https://weworkremotely.com/categories/remote-programming-jobs.rss"
]
print ("run successfully")

run successfully

In [38]:
def fetch_rss_jobs(feed_url):
    try:
        response = requests.get(feed_url, timeout=10)
        response.raise_for_status()
        
        root = ET.fromstring(response.content)
        
        jobs = []
        
        for item in root.findall(".//item"):
            job = {
                "title": item.findtext("title"),
                "link": item.findtext("link"),
                "published_date": item.findtext("pubDate"),
                "source_feed": feed_url,
                "collected_at": datetime.now(UTC)
            }
            
            jobs.append(job)
        
        return jobs
    
    except Exception as e:
        print(f"Error fetching {feed_url}: {e}")
        return []

In [44]:
df = pd.DataFrame(all_jobs)

In [45]:
all_jobs = []

for feed in RSS_FEEDS:
    jobs = fetch_rss_jobs(feed)
    all_jobs.extend(jobs)

len(all_jobs)

45

In [46]:
df["published_date"] = pd.to_datetime(df["published_date"], errors="coerce")

In [47]:
df = df.drop_duplicates(subset=["link"])
df.shape

(45, 5)

In [48]:
df.head

<bound method NDFrame.head of                                                 title  \
0      9 Mothers Defense (YC P26) Is Hiring in Austin
1   Converge (YC S23) Is Hiring a Founding Platfor...
2   Hive (YC S14) is hiring scrappy product manage...
3   Meticulous (YC S21) is hiring to redefine soft...
4   SigNoz (YC W21) is hiring for engineering, gro...
5   Multifactor (YC F25) Is Hiring an Engineering ...
6   Stardex (YC S21) is hiring customer success en...
7                    Structured AI (YC F25) Is Hiring
8   Roboflow (YC S20) Is Hiring a Security Enginee...
9                             Jiga (YC W21) Is Hiring
10  Reflex (YC W23) Is Hiring Software Engineers –...
11  Kyber (YC W23) Is Hiring an Enterprise Account...
12  Ubicloud (YC W24): Software Engineer – $95-$25...
13  LiteLLM (YC W23): Founding Reliability Enginee...
14  Bild AI (YC W25) Is Hiring Interns to Make Hou...
15                       Hightouch (YC S19) Is Hiring
16  Trellis AI (YC W24) is hiring deployment lead ...
17              Event Horizon Labs (YC W24) Is Hiring
18                      Corgi Labs (YC W23) Is Hiring
19  Verge (YC S15) Is Hiring a Director of Computa...
20  Media Cause: Front-End Website Developer (Cont...
21     The Global Talent Co.: Marketing Web Developer
22  Signet Jewelers: Web App Firewall Security Eng...
23                         Mobbin: UX Content Analyst
24  Michael Baker International: Oracle APEX Devel...
25                DeweyLearn Inc.: Python AI Engineer
26  The Church of Jesus Christ of Latter-day Saint...
27    Bright Vision Technologies: Front-End Developer
28    AHU Technologies: Business Analyst- Chicago, IL
29               Stellar AI: Senior Software Engineer
30              BHFT: Market Data Engineering Manager
31  Close: Senior Software Engineer - Backend/Pyth...
32                Jobgether: Remote Website Developer
33                         Soltech: MDM Data Engineer
34  AHU Technologies: SR Project Manager in Contin...
35  Magic: Web Development & Coding Specialist - F...
36                 Proton.ai: Senior Backend Engineer
37    Dusk Labs: Security Engineer  - Research & Test
38      Proxify AB: Senior Backend Developer (Python)
39  Proxify AB: Senior Backend Developer (Node.js ...
40    Proxify AB: Senior Fullstack Developer (Python)
41                           Dusk Labs: Test Engineer
42                 ALIQAN Technologies: Data Engineer
43  Blockchain & Climate Institute: UNPAID VOLUNTE...
44  Yoko Co: Development Contractors (Full Stack, ...

                                                 link  \
0   https://jobs.ashbyhq.com/9-mothers?utm_source=...
1   https://www.runconverge.com/careers/founding-p...
2                    https://jobs.ashbyhq.com/hive.co
3   https://jobs.ashbyhq.com/meticulous/3197ae3d-b...
4                           https://signoz.io/careers
5   https://www.ycombinator.com/companies/multifac...
6   https://www.ycombinator.com/companies/stardex/...
7   https://www.ycombinator.com/companies/structur...
8                        https://roboflow.com/careers
9                            https://jiga.io/about-us
10  https://www.ycombinator.com/companies/reflex/jobs
11  https://www.ycombinator.com/companies/kyber/jo...
12  https://www.ycombinator.com/companies/ubicloud...
13  https://www.ycombinator.com/companies/litellm/...
14          https://www.workatastartup.com/jobs/80596
15       https://hightouch.com/careers#open-positions
16  https://www.ycombinator.com/companies/trellis-...
17  https://www.ycombinator.com/companies/event-ho...
18  https://www.ycombinator.com/companies/corgi-la...
19            https://jobs.ashbyhq.com/verge-genomics
20  https://weworkremotely.com/remote-jobs/media-c...
21  https://weworkremotely.com/remote-jobs/the-glo...
22  https://weworkremotely.com/remote-jobs/signet-...
23  https://weworkremotely.com/remote-jobs/mobbin-...
24  https://weworkremotely.com/remote-jobs/michael...
25  https://weworkremotely.com/remote-jobs/deweyle...
26  https://weworkremotely.com/remote-jobs/the-chu...
27  https://weworkremotely.com/remote-jobs/bright-...
28  https://weworkremotely.com/remote-jobs/ahu-tec...
29  https://weworkremotely.com/remote-jobs/stellar...
30  https://weworkremotely.com/remote-jobs/bhft-ma...
31  https://weworkremotely.com/remote-jobs/close-s...
32  https://weworkremotely.com/remote-jobs/jobgeth...
33  https://weworkremotely.com/remote-jobs/soltech...
34  https://weworkremotely.com/remote-jobs/ahu-tec...
35  https://weworkremotely.com/remote-jobs/magic-w...
36  https://weworkremotely.com/remote-jobs/proton-...
37  https://weworkremotely.com/remote-jobs/dusk-la...
38  https://weworkremotely.com/remote-jobs/proxify...
39  https://weworkremotely.com/remote-jobs/proxify...
40  https://weworkremotely.com/remote-jobs/proxify...
41  https://weworkremotely.com/remote-jobs/dusk-la...
42  https://weworkremotely.com/remote-jobs/aliqan-...
43  https://weworkremotely.com/remote-jobs/blockch...
44  https://weworkremotely.com/remote-jobs/yoko-co...

              published_date  \
0  2026-03-14 13:45:04+00:00
1  2026-03-12 17:01:46+00:00
2  2026-03-12 14:32:46+00:00
3  2026-03-11 21:01:42+00:00
4  2026-03-07 17:01:14+00:00
5  2026-03-06 17:00:38+00:00
6  2026-03-06 07:02:08+00:00
7  2026-03-05 21:01:30+00:00
8  2026-03-04 17:49:44+00:00
9  2026-03-04 12:01:42+00:00
10 2026-03-02 17:01:20+00:00
11 2026-02-27 18:37:53+00:00
12 2026-02-27 08:45:02+00:00
13 2026-02-27 01:18:18+00:00
14 2026-02-26 17:00:25+00:00
15 2026-02-26 12:02:14+00:00
16 2026-02-25 17:02:12+00:00
17 2026-02-25 12:01:11+00:00
18 2026-02-25 01:01:02+00:00
19 2026-02-24 17:00:34+00:00
20 2026-02-19 16:05:54+00:00
21 2026-02-19 16:05:54+00:00
22 2026-02-19 16:05:54+00:00
23 2026-02-19 16:05:27+00:00
24 2026-02-19 16:05:27+00:00
25 2026-02-19 12:56:25+00:00
26 2026-02-18 22:00:58+00:00
27 2026-02-18 22:00:58+00:00
28 2026-02-18 22:00:57+00:00
29 2025-10-21 19:36:26+00:00
30 2026-02-18 16:46:41+00:00
31 2025-07-23 14:31:54+00:00
32 2026-02-17 22:19:58+00:00
33 2026-02-17 22:19:58+00:00
34 2026-02-17 22:19:58+00:00
35 2026-02-17 22:19:58+00:00
36 2025-01-22 23:59:57+00:00
37 2026-02-16 19:35:48+00:00
38 2026-02-16 11:17:19+00:00
39 2026-02-16 11:13:15+00:00
40 2026-02-16 11:11:26+00:00
41 2026-02-16 05:27:51+00:00
42 2026-02-13 22:01:39+00:00
43 2026-02-13 22:01:39+00:00
44 2026-02-13 20:06:45+00:00

                                          source_feed  \
0                              https://hnrss.org/jobs
1                              https://hnrss.org/jobs
2                              https://hnrss.org/jobs
3                              https://hnrss.org/jobs
4                              https://hnrss.org/jobs
5                              https://hnrss.org/jobs
6                              https://hnrss.org/jobs
7                              https://hnrss.org/jobs
8                              https://hnrss.org/jobs
9                              https://hnrss.org/jobs
10                             https://hnrss.org/jobs
11                             https://hnrss.org/jobs
12                             https://hnrss.org/jobs
13                             https://hnrss.org/jobs
14                             https://hnrss.org/jobs
15                             https://hnrss.org/jobs
16                             https://hnrss.org/jobs
17                             https://hnrss.org/jobs
18                             https://hnrss.org/jobs
19                             https://hnrss.org/jobs
20  https://weworkremotely.com/categories/remote-p...
21  https://weworkremotely.com/categories/remote-p...
22  https://weworkremotely.com/categories/remote-p...
23  https://weworkremotely.com/categories/remote-p...
24  https://weworkremotely.com/categories/remote-p...
25  https://weworkremotely.com/categories/remote-p...
26  https://weworkremotely.com/categories/remote-p...
27  https://weworkremotely.com/categories/remote-p...
28  https://weworkremotely.com/categories/remote-p...
29  https://weworkremotely.com/categories/remote-p...
30  https://weworkremotely.com/categories/remote-p...
31  https://weworkremotely.com/categories/remote-p...
32  https://weworkremotely.com/categories/remote-p...
33  https://weworkremotely.com/categories/remote-p...
34  https://weworkremotely.com/categories/remote-p...
35  https://weworkremotely.com/categories/remote-p...
36  https://weworkremotely.com/categories/remote-p...
37  https://weworkremotely.com/categories/remote-p...
38  https://weworkremotely.com/categories/remote-p...
39  https://weworkremotely.com/categories/remote-p...
40  https://weworkremotely.com/categories/remote-p...
41  https://weworkremotely.com/categories/remote-p...
42  https://weworkremotely.com/categories/remote-p...
43  https://weworkremotely.com/categories/remote-p...
44  https://weworkremotely.com/categories/remote-p...

                       collected_at
0  2026-03-15 19:45:50.356445+00:00
1  2026-03-15 19:45:50.356458+00:00
2  2026-03-15 19:45:50.356461+00:00
3  2026-03-15 19:45:50.356463+00:00
4  2026-03-15 19:45:50.356465+00:00
5  2026-03-15 19:45:50.356467+00:00
6  2026-03-15 19:45:50.356469+00:00
7  2026-03-15 19:45:50.356471+00:00
8  2026-03-15 19:45:50.356472+00:00
9  2026-03-15 19:45:50.356474+00:00
10 2026-03-15 19:45:50.356477+00:00
11 2026-03-15 19:45:50.356478+00:00
12 2026-03-15 19:45:50.356480+00:00
13 2026-03-15 19:45:50.356482+00:00
14 2026-03-15 19:45:50.356484+00:00
15 2026-03-15 19:45:50.356485+00:00
16 2026-03-15 19:45:50.356487+00:00
17 2026-03-15 19:45:50.356489+00:00
18 2026-03-15 19:45:50.356491+00:00
19 2026-03-15 19:45:50.356492+00:00
20 2026-03-15 19:45:50.750948+00:00
21 2026-03-15 19:45:50.750956+00:00
22 2026-03-15 19:45:50.750957+00:00
23 2026-03-15 19:45:50.750959+00:00
24 2026-03-15 19:45:50.750960+00:00
25 2026-03-15 19:45:50.750961+00:00
26 2026-03-15 19:45:50.750962+00:00
27 2026-03-15 19:45:50.750963+00:00
28 2026-03-15 19:45:50.750964+00:00
29 2026-03-15 19:45:50.750965+00:00
30 2026-03-15 19:45:50.750966+00:00
31 2026-03-15 19:45:50.750968+00:00
32 2026-03-15 19:45:50.750968+00:00
33 2026-03-15 19:45:50.750969+00:00
34 2026-03-15 19:45:50.750970+00:00
35 2026-03-15 19:45:50.750985+00:00
36 2026-03-15 19:45:50.750986+00:00
37 2026-03-15 19:45:50.750987+00:00
38 2026-03-15 19:45:50.750988+00:00
39 2026-03-15 19:45:50.750988+00:00
40 2026-03-15 19:45:50.750989+00:00
41 2026-03-15 19:45:50.750990+00:00
42 2026-03-15 19:45:50.750990+00:00
43 2026-03-15 19:45:50.750991+00:00
44 2026-03-15 19:45:50.750992+00:00  >

In [49]:
df

,title,link,published_date,source_feed,collected_at
0,9 Mothers Defense (YC P26) Is Hiring in Austin,https://jobs.ashbyhq.com/9-mothers?utm_source=...,2026-03-14 13:45:04+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356445+00:00
1,Converge (YC S23) Is Hiring a Founding Platfor...,https://www.runconverge.com/careers/founding-p...,2026-03-12 17:01:46+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356458+00:00
2,Hive (YC S14) is hiring scrappy product manage...,https://jobs.ashbyhq.com/hive.co,2026-03-12 14:32:46+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356461+00:00
3,Meticulous (YC S21) is hiring to redefine soft...,https://jobs.ashbyhq.com/meticulous/3197ae3d-b...,2026-03-11 21:01:42+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356463+00:00
4,"SigNoz (YC W21) is hiring for engineering, gro...",https://signoz.io/careers,2026-03-07 17:01:14+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356465+00:00
5,Multifactor (YC F25) Is Hiring an Engineering ...,https://www.ycombinator.com/companies/multifac...,2026-03-06 17:00:38+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356467+00:00
6,Stardex (YC S21) is hiring customer success en...,https://www.ycombinator.com/companies/stardex/...,2026-03-06 07:02:08+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356469+00:00
7,Structured AI (YC F25) Is Hiring,https://www.ycombinator.com/companies/structur...,2026-03-05 21:01:30+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356471+00:00
8,Roboflow (YC S20) Is Hiring a Security Enginee...,https://roboflow.com/careers,2026-03-04 17:49:44+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356472+00:00
9,Jiga (YC W21) Is Hiring,https://jiga.io/about-us,2026-03-04 12:01:42+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356474+00:00
10,Reflex (YC W23) Is Hiring Software Engineers –...,https://www.ycombinator.com/companies/reflex/jobs,2026-03-02 17:01:20+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356477+00:00
11,Kyber (YC W23) Is Hiring an Enterprise Account...,https://www.ycombinator.com/companies/kyber/jo...,2026-02-27 18:37:53+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356478+00:00
12,Ubicloud (YC W24): Software Engineer – $95-$25...,https://www.ycombinator.com/companies/ubicloud...,2026-02-27 08:45:02+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356480+00:00
13,LiteLLM (YC W23): Founding Reliability Enginee...,https://www.ycombinator.com/companies/litellm/...,2026-02-27 01:18:18+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356482+00:00
14,Bild AI (YC W25) Is Hiring Interns to Make Hou...,https://www.workatastartup.com/jobs/80596,2026-02-26 17:00:25+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356484+00:00
15,Hightouch (YC S19) Is Hiring,https://hightouch.com/careers#open-positions,2026-02-26 12:02:14+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356485+00:00
16,Trellis AI (YC W24) is hiring deployment lead ...,https://www.ycombinator.com/companies/trellis-...,2026-02-25 17:02:12+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356487+00:00
17,Event Horizon Labs (YC W24) Is Hiring,https://www.ycombinator.com/companies/event-ho...,2026-02-25 12:01:11+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356489+00:00
18,Corgi Labs (YC W23) Is Hiring,https://www.ycombinator.com/companies/corgi-la...,2026-02-25 01:01:02+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356491+00:00
19,Verge (YC S15) Is Hiring a Director of Computa...,https://jobs.ashbyhq.com/verge-genomics,2026-02-24 17:00:34+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356492+00:00
20,Media Cause: Front-End Website Developer (Cont...,https://weworkremotely.com/remote-jobs/media-c...,2026-02-19 16:05:54+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750948+00:00
21,The Global Talent Co.: Marketing Web Developer,https://weworkremotely.com/remote-jobs/the-glo...,2026-02-19 16:05:54+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750956+00:00
22,Signet Jewelers: Web App Firewall Security Eng...,https://weworkremotely.com/remote-jobs/signet-...,2026-02-19 16:05:54+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750957+00:00
23,Mobbin: UX Content Analyst,https://weworkremotely.com/remote-jobs/mobbin-...,2026-02-19 16:05:27+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750959+00:00
24,Michael Baker International: Oracle APEX Devel...,https://weworkremotely.com/remote-jobs/michael...,2026-02-19 16:05:27+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750960+00:00
25,DeweyLearn Inc.: Python AI Engineer,https://weworkremotely.com/remote-jobs/deweyle...,2026-02-19 12:56:25+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750961+00:00
26,The Church of Jesus Christ of Latter-day Saint...,https://weworkremotely.com/remote-jobs/the-chu...,2026-02-18 22:00:58+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750962+00:00
27,Bright Vision Technologies: Front-End Developer,https://weworkremotely.com/remote-jobs/bright-...,2026-02-18 22:00:58+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750963+00:00
28,"AHU Technologies: Business Analyst- Chicago, IL",https://weworkremotely.com/remote-jobs/ahu-tec...,2026-02-18 22:00:57+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750964+00:00
29,Stellar AI: Senior Software Engineer,https://weworkremotely.com/remote-jobs/stellar...,2025-10-21 19:36:26+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750965+00:00
30,BHFT: Market Data Engineering Manager,https://weworkremotely.com/remote-jobs/bhft-ma...,2026-02-18 16:46:41+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750966+00:00
31,Close: Senior Software Engineer - Backend/Pyth...,https://weworkremotely.com/remote-jobs/close-s...,2025-07-23 14:31:54+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750968+00:00
32,Jobgether: Remote Website Developer,https://weworkremotely.com/remote-jobs/jobgeth...,2026-02-17 22:19:58+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750968+00:00
33,Soltech: MDM Data Engineer,https://weworkremotely.com/remote-jobs/soltech...,2026-02-17 22:19:58+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750969+00:00
34,AHU Technologies: SR Project Manager in Contin...,https://weworkremotely.com/remote-jobs/ahu-tec...,2026-02-17 22:19:58+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750970+00:00
35,Magic: Web Development & Coding Specialist - F...,https://weworkremotely.com/remote-jobs/magic-w...,2026-02-17 22:19:58+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750985+00:00
36,Proton.ai: Senior Backend Engineer,https://weworkremotely.com/remote-jobs/proton-...,2025-01-22 23:59:57+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750986+00:00
37,Dusk Labs: Security Engineer - Research & Test,https://weworkremotely.com/remote-jobs/dusk-la...,2026-02-16 19:35:48+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750987+00:00
38,Proxify AB: Senior Backend Developer (Python),https://weworkremotely.com/remote-jobs/proxify...,2026-02-16 11:17:19+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750988+00:00
39,Proxify AB: Senior Backend Developer (Node.js ...,https://weworkremotely.com/remote-jobs/proxify...,2026-02-16 11:13:15+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750988+00:00
40,Proxify AB: Senior Fullstack Developer (Python),https://weworkremotely.com/remote-jobs/proxify...,2026-02-16 11:11:26+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750989+00:00
41,Dusk Labs: Test Engineer,https://weworkremotely.com/remote-jobs/dusk-la...,2026-02-16 05:27:51+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750990+00:00
42,ALIQAN Technologies: Data Engineer,https://weworkremotely.com/remote-jobs/aliqan-...,2026-02-13 22:01:39+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750990+00:00
43,Blockchain & Climate Institute: UNPAID VOLUNTE...,https://weworkremotely.com/remote-jobs/blockch...,2026-02-13 22:01:39+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750991+00:00
44,"Yoko Co: Development Contractors (Full Stack, ...",https://weworkremotely.com/remote-jobs/yoko-co...,2026-02-13 20:06:45+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750992+00:00

In [50]:
df = df.reset_index(drop=True)

In [51]:
df

,title,link,published_date,source_feed,collected_at
0,9 Mothers Defense (YC P26) Is Hiring in Austin,https://jobs.ashbyhq.com/9-mothers?utm_source=...,2026-03-14 13:45:04+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356445+00:00
1,Converge (YC S23) Is Hiring a Founding Platfor...,https://www.runconverge.com/careers/founding-p...,2026-03-12 17:01:46+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356458+00:00
2,Hive (YC S14) is hiring scrappy product manage...,https://jobs.ashbyhq.com/hive.co,2026-03-12 14:32:46+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356461+00:00
3,Meticulous (YC S21) is hiring to redefine soft...,https://jobs.ashbyhq.com/meticulous/3197ae3d-b...,2026-03-11 21:01:42+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356463+00:00
4,"SigNoz (YC W21) is hiring for engineering, gro...",https://signoz.io/careers,2026-03-07 17:01:14+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356465+00:00
5,Multifactor (YC F25) Is Hiring an Engineering ...,https://www.ycombinator.com/companies/multifac...,2026-03-06 17:00:38+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356467+00:00
6,Stardex (YC S21) is hiring customer success en...,https://www.ycombinator.com/companies/stardex/...,2026-03-06 07:02:08+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356469+00:00
7,Structured AI (YC F25) Is Hiring,https://www.ycombinator.com/companies/structur...,2026-03-05 21:01:30+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356471+00:00
8,Roboflow (YC S20) Is Hiring a Security Enginee...,https://roboflow.com/careers,2026-03-04 17:49:44+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356472+00:00
9,Jiga (YC W21) Is Hiring,https://jiga.io/about-us,2026-03-04 12:01:42+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356474+00:00
10,Reflex (YC W23) Is Hiring Software Engineers –...,https://www.ycombinator.com/companies/reflex/jobs,2026-03-02 17:01:20+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356477+00:00
11,Kyber (YC W23) Is Hiring an Enterprise Account...,https://www.ycombinator.com/companies/kyber/jo...,2026-02-27 18:37:53+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356478+00:00
12,Ubicloud (YC W24): Software Engineer – $95-$25...,https://www.ycombinator.com/companies/ubicloud...,2026-02-27 08:45:02+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356480+00:00
13,LiteLLM (YC W23): Founding Reliability Enginee...,https://www.ycombinator.com/companies/litellm/...,2026-02-27 01:18:18+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356482+00:00
14,Bild AI (YC W25) Is Hiring Interns to Make Hou...,https://www.workatastartup.com/jobs/80596,2026-02-26 17:00:25+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356484+00:00
15,Hightouch (YC S19) Is Hiring,https://hightouch.com/careers#open-positions,2026-02-26 12:02:14+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356485+00:00
16,Trellis AI (YC W24) is hiring deployment lead ...,https://www.ycombinator.com/companies/trellis-...,2026-02-25 17:02:12+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356487+00:00
17,Event Horizon Labs (YC W24) Is Hiring,https://www.ycombinator.com/companies/event-ho...,2026-02-25 12:01:11+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356489+00:00
18,Corgi Labs (YC W23) Is Hiring,https://www.ycombinator.com/companies/corgi-la...,2026-02-25 01:01:02+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356491+00:00
19,Verge (YC S15) Is Hiring a Director of Computa...,https://jobs.ashbyhq.com/verge-genomics,2026-02-24 17:00:34+00:00,https://hnrss.org/jobs,2026-03-15 19:45:50.356492+00:00
20,Media Cause: Front-End Website Developer (Cont...,https://weworkremotely.com/remote-jobs/media-c...,2026-02-19 16:05:54+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750948+00:00
21,The Global Talent Co.: Marketing Web Developer,https://weworkremotely.com/remote-jobs/the-glo...,2026-02-19 16:05:54+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750956+00:00
22,Signet Jewelers: Web App Firewall Security Eng...,https://weworkremotely.com/remote-jobs/signet-...,2026-02-19 16:05:54+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750957+00:00
23,Mobbin: UX Content Analyst,https://weworkremotely.com/remote-jobs/mobbin-...,2026-02-19 16:05:27+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750959+00:00
24,Michael Baker International: Oracle APEX Devel...,https://weworkremotely.com/remote-jobs/michael...,2026-02-19 16:05:27+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750960+00:00
25,DeweyLearn Inc.: Python AI Engineer,https://weworkremotely.com/remote-jobs/deweyle...,2026-02-19 12:56:25+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750961+00:00
26,The Church of Jesus Christ of Latter-day Saint...,https://weworkremotely.com/remote-jobs/the-chu...,2026-02-18 22:00:58+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750962+00:00
27,Bright Vision Technologies: Front-End Developer,https://weworkremotely.com/remote-jobs/bright-...,2026-02-18 22:00:58+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750963+00:00
28,"AHU Technologies: Business Analyst- Chicago, IL",https://weworkremotely.com/remote-jobs/ahu-tec...,2026-02-18 22:00:57+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750964+00:00
29,Stellar AI: Senior Software Engineer,https://weworkremotely.com/remote-jobs/stellar...,2025-10-21 19:36:26+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750965+00:00
30,BHFT: Market Data Engineering Manager,https://weworkremotely.com/remote-jobs/bhft-ma...,2026-02-18 16:46:41+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750966+00:00
31,Close: Senior Software Engineer - Backend/Pyth...,https://weworkremotely.com/remote-jobs/close-s...,2025-07-23 14:31:54+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750968+00:00
32,Jobgether: Remote Website Developer,https://weworkremotely.com/remote-jobs/jobgeth...,2026-02-17 22:19:58+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750968+00:00
33,Soltech: MDM Data Engineer,https://weworkremotely.com/remote-jobs/soltech...,2026-02-17 22:19:58+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750969+00:00
34,AHU Technologies: SR Project Manager in Contin...,https://weworkremotely.com/remote-jobs/ahu-tec...,2026-02-17 22:19:58+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750970+00:00
35,Magic: Web Development & Coding Specialist - F...,https://weworkremotely.com/remote-jobs/magic-w...,2026-02-17 22:19:58+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750985+00:00
36,Proton.ai: Senior Backend Engineer,https://weworkremotely.com/remote-jobs/proton-...,2025-01-22 23:59:57+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750986+00:00
37,Dusk Labs: Security Engineer - Research & Test,https://weworkremotely.com/remote-jobs/dusk-la...,2026-02-16 19:35:48+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750987+00:00
38,Proxify AB: Senior Backend Developer (Python),https://weworkremotely.com/remote-jobs/proxify...,2026-02-16 11:17:19+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750988+00:00
39,Proxify AB: Senior Backend Developer (Node.js ...,https://weworkremotely.com/remote-jobs/proxify...,2026-02-16 11:13:15+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750988+00:00
40,Proxify AB: Senior Fullstack Developer (Python),https://weworkremotely.com/remote-jobs/proxify...,2026-02-16 11:11:26+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750989+00:00
41,Dusk Labs: Test Engineer,https://weworkremotely.com/remote-jobs/dusk-la...,2026-02-16 05:27:51+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750990+00:00
42,ALIQAN Technologies: Data Engineer,https://weworkremotely.com/remote-jobs/aliqan-...,2026-02-13 22:01:39+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750990+00:00
43,Blockchain & Climate Institute: UNPAID VOLUNTE...,https://weworkremotely.com/remote-jobs/blockch...,2026-02-13 22:01:39+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750991+00:00
44,"Yoko Co: Development Contractors (Full Stack, ...",https://weworkremotely.com/remote-jobs/yoko-co...,2026-02-13 20:06:45+00:00,https://weworkremotely.com/categories/remote-p...,2026-03-15 19:45:50.750992+00:00